### ISSUE TITLE
List of potential attacks to the system

### ISSUE THREAD

**Issue by albero94** [albero94/gw-blockchain-cardboard-killers#17]
•	What are the guarantees?
•	AI to make the system work?

**Comment by swilliams9671** [comment]
Two possible attacks are as follows: 1) Duplication or a copy of the sensor to send “false” data that does not represent the intended physical product. E.g. If many fake products can mimic the sending of the same sensor data (and the Blockchain doesn’t know the difference between many of the same signatures), a Denial of Service attack can occur or the system can break. 2) Physical tampering of the sensors can result in incorrect data. E.g. A sensor is removed or damaged and does not report the correct data to the Blockchain.
